[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs", "npm"]

[phases.build]
cmds = [
    "composer install --no-dev --no-interaction",
    "npm install && npm run build",
    "php artisan view:cache"
]
