[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs", "npm"]

[phases.build]
cmds = [
    "composer install --no-dev --no-interaction",
    "npm install && npm run build",
    "mkdir -p storage/framework/{sessions,views,cache} bootstrap/cache",
    "chmod -R 775 storage bootstrap/cache"
]
